apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-db
  template:
    metadata:
      labels:
        app: backend-db
    spec:
      containers:
        - name: backend-db
          image: aincolgon/backend-db:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgresql+asyncpg://postgres:postgres@postgres:5432/app_db"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-db
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: backend-db
