apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-project-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-project-react
  template:
    metadata:
      labels:
        app: micro-project-react
    spec:
      containers:
        - name: micro-project-react
          image: aincolgon/micro-project-react:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: micro-project-react
  labels:
    app: micro-project-react
spec:
  selector:
    app: micro-project-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
